---
title: "R Notebook"
output: html_notebook
---


```{r}
library(keyring)
library(RPostgreSQL)

keyring_unlock("local")
username <- key_get(service = "postgresql_username", keyring = "local")
password <- key_get(service = "postgresql_password", keyring = "local")
keyring_lock("local")

db_connect <- dbConnect(drv = PostgreSQL(max.con = 1), user = username, password = password, dbname = "acme_employees", host = "localhost")

rm(username, password)
```

```{r}
employees_df <- dbGetQuery(db_connect, 
                           "SELECT *
                           FROM employees")
employees_df
```

```{r}
dbGetQuery(db_connect, 
           "SELECT *, CONCAT(first_name, ' ', last_name) AS full_name
           FROM employees")
```

```{r}
dbGetQuery(db_connect, 
           "SELECT e.id, e.first_name, e.last_name, e.email, t.name AS team_name
           FROM employees AS e INNER JOIN teams AS t
           ON e.team_id = t.id")
```

```{r}
dbGetQuery(db_connect, 
           "SELECT COUNT(e.*), t.name AS team_name
           FROM teams AS t LEFT JOIN employees AS e
           ON t.id = e.team_id
           GROUP BY t.name")
```

```{r}
dbGetQuery(db_connect, 
           "SELECT * 
           FROM employees
           WHERE email = '%@%' OR email IS NOT NULL")
```

```{r}
feedbacks_df <- dbGetQuery(db_connect, 
                           "SELECT * FROM feedbacks")
```

```{r}
dbGetQuery(db_connect, 
           "SELECT e.id, e.first_name, e.last_name, f.date
           FROM employees AS e INNER JOIN feedbacks AS f
           ON e.id = f.employee_id
           ORDER BY f.date DESC")
```

```{r}
dbGetQuery(db_connect, 
           "SELECT COUNT(e.first_name), t.name AS team_name
           FROM employees AS e INNER JOIN teams AS t
           ON e.team_id = t.id
           WHERE first_name LIKE '_'
           GROUP BY t.name")
```


sentiment analysis
```{r}
positive_words <- c("great", "good", "happy", "content", "fulfilled", "fulfilled", "positive", "positives", "cheerful", "nice", "ambition", "ambitions", "ambitious", "friendly", "progress", "joy", "fast", "achieve", "achieving", "achievements", "best", "better",  "unlimited", "pros", "competitive", "opportunity", "advancement", "friendly", "smart", "interesting", "challenging", "grow", "caring", "balance", "helpful")


negative_words <- c("worse", "worsening", "worst", "slow", "sluggish", "impatient", "unfulfilled", "unfulfilling", "negative", "bad", "limited", "limit", "limitations", "cons", "frustrated", "frustrating", "frustration", "dull", "boring", "politics", "political", "ignore", "ignored", "ignoring", "sad", "depressed", "depressing", "nasty", "stress", "stresses", "stressed", "horrid", "horrible", "terrible", "deadline", "deadlines", "uncaring", "remote")
```

```{r}
clean_message <- function(message){
  lowered <- tolower(message)
  punct <- gsub(pattern = ".", replacement = "", x = lowered, fixed = TRUE)
  punct <- gsub(pattern = ",", replacement = "", x = punct, fixed = TRUE)
  punct <- gsub(pattern = "!", replacement = "", x = punct, fixed = TRUE)
  punct <- gsub(pattern = "'", replacement = "", x = punct, fixed = TRUE)
  punct <- gsub(pattern = "?", replacement = "", x = punct, fixed = TRUE)
  punct <- gsub(pattern = ":", replacement = "", x = punct, fixed = TRUE)
  punct <- gsub(pattern = ";", replacement = "", x = punct, fixed = TRUE)
  return(punct)
}

clean_message("Good company, competitive salaries, nice colleagues, good location, but the food in the canteen is just terrible!")

#to do: start each comment at 0. for every positive word, increase its score by 1. for every negative word, decrease its score by 1. at the end, its score will be its positivity.

sentiment_scoring <- function(comment){
  for (words in comment){
    score <- 0
    
    print(score)
  }
}
```

```{r}
sentiment_scoring("good company competitive salaries nice colleagues good location but the food in the canteen is just terrible")
```




```{r}
#dbDisconnect(db_connect)
```

